#[path = "src/docs_support.rs"]
mod docs_support;

use docs_support::{collect_corpus_sources, derive_doc_id, extract_description, extract_title, DocKind};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .ancestors()
        .nth(4)
        .expect("repo root")
        .to_path_buf();

    emit_rerun_markers(&repo_root);

    let sources = collect_corpus_sources(&repo_root).expect("embedded docs corpus");
    let out_file = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_docs.rs");
    let mut generated = String::from("// @generated by build.rs\n");
    generated.push_str("static EMBEDDED_DOC_SPECS: &[EmbeddedDocSpec] = &[\n");

    for source in sources {
        let contents = fs::read_to_string(&source.absolute_path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", source.absolute_path.display()));
        let doc_id = derive_doc_id(source.kind, &source.relative_path)
            .unwrap_or_else(|error| panic!("failed to derive doc id for {}: {error}", source.relative_path));
        let title = extract_title(source.kind, &source.relative_path, &contents);
        let description = extract_description(source.kind, &contents, &title);

        generated.push_str("    EmbeddedDocSpec {\n");
        generated.push_str(&format!("        doc_id: {},\n", rust_string(&doc_id)));
        generated.push_str(&format!(
            "        kind: {},\n",
            generated_kind(source.kind)
        ));
        generated.push_str(&format!("        title: {},\n", rust_string(&title)));
        generated.push_str(&format!(
            "        path: {},\n",
            rust_string(&source.relative_path)
        ));
        generated.push_str(&format!(
            "        description: {},\n",
            rust_string(&description)
        ));
        generated.push_str(&format!(
            "        text: include_str!({}),\n",
            rust_string(&source.absolute_path.to_string_lossy())
        ));
        generated.push_str("    },\n");
    }

    generated.push_str("];\n");
    fs::write(&out_file, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", out_file.display()));
}

fn emit_rerun_markers(repo_root: &Path) {
    for relative in [
        "README.md",
        "language/README.md",
        "language/docs",
        "language/spec",
        "website/articles",
    ] {
        println!("cargo:rerun-if-changed={}", repo_root.join(relative).display());
    }

    for source in collect_corpus_sources(repo_root).expect("rerun corpus sources") {
        println!("cargo:rerun-if-changed={}", source.absolute_path.display());
    }
}

fn generated_kind(kind: DocKind) -> &'static str {
    match kind {
        DocKind::Guide => "DocKind::Guide",
        DocKind::Docs => "DocKind::Docs",
        DocKind::Spec => "DocKind::Spec",
        DocKind::Article => "DocKind::Article",
    }
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}
